package input

var ElastoDynSchema = NewSchema("ElastoDyn", []SchemaEntry{
	{Heading: "ElastoDyn Input File"},
	{Keyword: "Title", Type: String, Format: formatTitle, Parse: parseTitle},
	{Heading: "Simulation Control"},
	{Keyword: "Echo", Type: Bool, Desc: `Echo input data to <RootName>.ech`, Unit: "flag"},
	{Keyword: "Method", Type: Int, Desc: `Integration method`, Options: []Option{{1, "RK4"}, {2, "AB4"}, {3, "ABM4"}}},
	{Keyword: "DT", Type: Float, Desc: `Integration time step`, Unit: "sec", CanBeDefault: true},
	{Heading: "Degrees Of Freedom"},
	{Keyword: "FlapDOF1", Type: Bool, Desc: `First flapwise blade mode DOF`, Unit: "flag"},
	{Keyword: "FlapDOF2", Type: Bool, Desc: `Second flapwise blade mode DOF`, Unit: "flag"},
	{Keyword: "EdgeDOF", Type: Bool, Desc: `First edgewise blade mode DOF`, Unit: "flag"},
	{Keyword: "TeetDOF", Type: Bool, Desc: `Rotor-teeter DOF [unused for 3 blades]`, Unit: "flag"},
	{Keyword: "DrTrDOF", Type: Bool, Desc: `Drivetrain rotational-flexibility DOF`, Unit: "flag"},
	{Keyword: "GenDOF", Type: Bool, Desc: `Generator DOF`, Unit: "flag"},
	{Keyword: "YawDOF", Type: Bool, Desc: `Yaw DOF`, Unit: "flag"},
	{Keyword: "TwFADOF1", Type: Bool, Desc: `First fore-aft tower bending-mode DOF`, Unit: "flag"},
	{Keyword: "TwFADOF2", Type: Bool, Desc: `Second fore-aft tower bending-mode DOF`, Unit: "flag"},
	{Keyword: "TwSSDOF1", Type: Bool, Desc: `First side-to-side tower bending-mode DOF`, Unit: "flag"},
	{Keyword: "TwSSDOF2", Type: Bool, Desc: `Second side-to-side tower bending-mode DOF`, Unit: "flag"},
	{Keyword: "PtfmSgDOF", Type: Bool, Desc: `Platform horizontal surge translation DOF`, Unit: "flag"},
	{Keyword: "PtfmSwDOF", Type: Bool, Desc: `Platform horizontal sway translation DOF`, Unit: "flag"},
	{Keyword: "PtfmHvDOF", Type: Bool, Desc: `Platform vertical heave translation DOF`, Unit: "flag"},
	{Keyword: "PtfmRDOF", Type: Bool, Desc: `Platform roll tilt rotation DOF`, Unit: "flag"},
	{Keyword: "PtfmPDOF", Type: Bool, Desc: `Platform pitch tilt rotation DOF`, Unit: "flag"},
	{Keyword: "PtfmYDOF", Type: Bool, Desc: `Platform yaw rotation DOF`, Unit: "flag"},
	{Heading: "Initial Conditions"},
	{Keyword: "OoPDefl", Type: Float, Desc: `Initial out-of-plane blade-tip displacement`, Unit: "meters"},
	{Keyword: "IPDefl", Type: Float, Desc: `Initial in-plane blade-tip deflection`, Unit: "meters"},
	{Keyword: "BlPitch(1)", Type: Float, Desc: `Blade 1 initial pitch`, Unit: "degrees"},
	{Keyword: "BlPitch(2)", Type: Float, Desc: `Blade 2 initial pitch`, Unit: "degrees"},
	{Keyword: "BlPitch(3)", Type: Float, Desc: `Blade 3 initial pitch [unused for 2 blades]`, Unit: "degrees"},
	{Keyword: "TeetDefl", Type: Float, Desc: `Initial or fixed teeter angle [unused for 3 blades]`, Unit: "degrees"},
	{Keyword: "Azimuth", Type: Float, Desc: `Initial azimuth angle for blade 1`, Unit: "degrees"},
	{Keyword: "RotSpeed", Type: Float, Desc: `Initial or fixed rotor speed`, Unit: "rpm"},
	{Keyword: "NacYaw", Type: Float, Desc: `Initial or fixed nacelle-yaw angle`, Unit: "degrees"},
	{Keyword: "TTDspFA", Type: Float, Desc: `Initial fore-aft tower-top displacement`, Unit: "meters"},
	{Keyword: "TTDspSS", Type: Float, Desc: `Initial side-to-side tower-top displacement`, Unit: "meters"},
	{Keyword: "PtfmSurge", Type: Float, Desc: `Initial or fixed horizontal surge translational displacement of platform`, Unit: "meters"},
	{Keyword: "PtfmSway", Type: Float, Desc: `Initial or fixed horizontal sway translational displacement of platform`, Unit: "meters"},
	{Keyword: "PtfmHeave", Type: Float, Desc: `Initial or fixed vertical heave translational displacement of platform`, Unit: "meters"},
	{Keyword: "PtfmRoll", Type: Float, Desc: `Initial or fixed roll tilt rotational displacement of platform`, Unit: "degrees"},
	{Keyword: "PtfmPitch", Type: Float, Desc: `Initial or fixed pitch tilt rotational displacement of platform`, Unit: "degrees"},
	{Keyword: "PtfmYaw", Type: Float, Desc: `Initial or fixed yaw rotational displacement of platform`, Unit: "degrees"},
	{Heading: "Turbine Configuration"},
	{Keyword: "NumBl", Type: Int, Desc: `Number of blades`, Unit: "-"},
	{Keyword: "TipRad", Type: Float, Desc: `The distance from the rotor apex to the blade tip`, Unit: "meters"},
	{Keyword: "HubRad", Type: Float, Desc: `The distance from the rotor apex to the blade root`, Unit: "meters"},
	{Keyword: "PreCone(1)", Type: Float, Desc: `Blade 1 cone angle`, Unit: "degrees"},
	{Keyword: "PreCone(2)", Type: Float, Desc: `Blade 2 cone angle`, Unit: "degrees"},
	{Keyword: "PreCone(3)", Type: Float, Desc: `Blade 3 cone angle [unused for 2 blades]`, Unit: "degrees"},
	{Keyword: "HubCM", Type: Float, Desc: `Distance from rotor apex to hub mass [positive downwind]`, Unit: "meters"},
	{Keyword: "UndSling", Type: Float, Desc: `Undersling length [distance from teeter pin to the rotor apex] , Unit:"meters"[unused for 3 blades]`},
	{Keyword: "Delta3", Type: Float, Desc: `Delta-3 angle for teetering rotors [unused for 3 blades]`, Unit: "degrees"},
	{Keyword: "AzimB1Up", Type: Float, Desc: `Azimuth value to use for I/O when blade 1 points up`, Unit: "degrees"},
	{Keyword: "OverHang", Type: Float, Desc: `Distance from yaw axis to rotor apex [3 blades] or teeter pin [2 blades]`, Unit: "meters"},
	{Keyword: "ShftGagL", Type: Float, Desc: `Distance from rotor apex [3 blades] or teeter pin [2 blades] to shaft strain gages [positive for upwind rotors]`, Unit: "meters"},
	{Keyword: "ShftTilt", Type: Float, Desc: `Rotor shaft tilt angle`, Unit: "degrees"},
	{Keyword: "NacCMxn", Type: Float, Desc: `Downwind distance from the tower-top to the nacelle CM`, Unit: "meters"},
	{Keyword: "NacCMyn", Type: Float, Desc: `Lateral  distance from the tower-top to the nacelle CM`, Unit: "meters"},
	{Keyword: "NacCMzn", Type: Float, Desc: `Vertical distance from the tower-top to the nacelle CM`, Unit: "meters"},
	{Keyword: "NcIMUxn", Type: Float, Desc: `Downwind distance from the tower-top to the nacelle IMU`, Unit: "meters"},
	{Keyword: "NcIMUyn", Type: Float, Desc: `Lateral  distance from the tower-top to the nacelle IMU`, Unit: "meters"},
	{Keyword: "NcIMUzn", Type: Float, Desc: `Vertical distance from the tower-top to the nacelle IMU`, Unit: "meters"},
	{Keyword: "Twr2Shft", Type: Float, Desc: `Vertical distance from the tower-top to the rotor shaft`, Unit: "meters"},
	{Keyword: "TowerHt", Type: Float, Desc: `Height of tower above ground level [onshore] or MSL [offshore]`, Unit: "meters"},
	{Keyword: "TowerBsHt", Type: Float, Desc: `Height of tower base above ground level [onshore] or MSL [offshore]`, Unit: "meters"},
	{Keyword: "PtfmCMxt", Type: Float, Desc: `Downwind distance from the ground level [onshore] or MSL [offshore] to the platform CM`, Unit: "meters"},
	{Keyword: "PtfmCMyt", Type: Float, Desc: `Lateral distance from the ground level [onshore] or MSL [offshore] to the platform CM`, Unit: "meters"},
	{Keyword: "PtfmCMzt", Type: Float, Desc: `Vertical distance from the ground level [onshore] or MSL [offshore] to the platform CM`, Unit: "meters"},
	{Keyword: "PtfmRefzt", Type: Float, Desc: `Vertical distance from the ground level [onshore] or MSL [offshore] to the platform reference point`, Unit: "meters"},
	{Heading: "Mass And Inertia"},
	{Keyword: "TipMass(1)", Type: Float, Desc: `Tip-brake mass, blade 1`, Unit: "kg"},
	{Keyword: "TipMass(2)", Type: Float, Desc: `Tip-brake mass, blade 2`, Unit: "kg"},
	{Keyword: "TipMass(3)", Type: Float, Desc: `Tip-brake mass, blade 3 [unused for 2 blades]`, Unit: "kg"},
	{Keyword: "HubMass", Type: Float, Desc: `Hub mass`, Unit: "kg"},
	{Keyword: "HubIner", Type: Float, Desc: `Hub inertia about rotor axis [3 blades] or teeter axis [2 blades]`, Unit: "kg m^2"},
	{Keyword: "GenIner", Type: Float, Desc: `Generator inertia about HSS`, Unit: "kg m^2"},
	{Keyword: "NacMass", Type: Float, Desc: `Nacelle mass`, Unit: "kg"},
	{Keyword: "NacYIner", Type: Float, Desc: `Nacelle inertia about yaw axis`, Unit: "kg m^2"},
	{Keyword: "YawBrMass", Type: Float, Desc: `Yaw bearing mass`, Unit: "kg"},
	{Keyword: "PtfmMass", Type: Float, Desc: `Platform mass`, Unit: "kg"},
	{Keyword: "PtfmRIner", Type: Float, Desc: `Platform inertia for roll tilt rotation about the platform CM`, Unit: "kg m^2"},
	{Keyword: "PtfmPIner", Type: Float, Desc: `Platform inertia for pitch tilt rotation about the platform CM`, Unit: "kg m^2"},
	{Keyword: "PtfmYIner", Type: Float, Desc: `Platform inertia for yaw rotation about the platform CM`, Unit: "kg m^2"},
	{Heading: "Blade"},
	{Keyword: "BldNodes", Type: Int, Desc: `Number of blade nodes (per blade) used for analysis`, Unit: "-"},
	{Keyword: "BldFile(1)", Type: String, Desc: `Name of file containing properties for blade 1 (quoted string)`},
	{Keyword: "BldFile(2)", Type: String, Desc: `Name of file containing properties for blade 2 (quoted string)`},
	{Keyword: "BldFile(3)", Type: String, Desc: `Name of file containing properties for blade 3 (quoted string) [unused for 2 blades]`},
	{Heading: "Rotor-Teeter"},
	{Keyword: "TeetMod", Type: Int, Desc: `Rotor-teeter spring/damper model (switch) [unused for 3 blades]`, Options: []Option{{0, "none"}, {1, "standard"}, {2, "user-defined from routine UserTeet"}}},
	{Keyword: "TeetDmpP", Type: Float, Desc: `Rotor-teeter damper position [used only for 2 blades and when TeetMod=1]`, Unit: "degrees"},
	{Keyword: "TeetDmp", Type: Float, Desc: `Rotor-teeter damping constant [used only for 2 blades and when TeetMod=1]`, Unit: "N-m/(rad/s)"},
	{Keyword: "TeetCDmp", Type: Float, Desc: `Rotor-teeter rate-independent Coulomb-damping moment (N-m) [used only for 2 blades and when TeetMod=1]`},
	{Keyword: "TeetSStP", Type: Float, Desc: `Rotor-teeter soft-stop position [used only for 2 blades and when TeetMod=1]`, Unit: "degrees"},
	{Keyword: "TeetHStP", Type: Float, Desc: `Rotor-teeter hard-stop position [used only for 2 blades and when TeetMod=1]`, Unit: "degrees"},
	{Keyword: "TeetSSSp", Type: Float, Desc: `Rotor-teeter soft-stop linear-spring constant [used only for 2 blades and when TeetMod=1]`, Unit: "N-m/rad"},
	{Keyword: "TeetHSSp", Type: Float, Desc: `Rotor-teeter hard-stop linear-spring constant [used only for 2 blades and when TeetMod=1]`, Unit: "N-m/rad"},
	{Heading: "Drivetrain"},
	{Keyword: "GBoxEff", Type: Float, Desc: `Gearbox efficiency`, Unit: "%"},
	{Keyword: "GBRatio", Type: Float, Desc: `Gearbox ratio`, Unit: "-"},
	{Keyword: "DTTorSpr", Type: Float, Desc: `Drivetrain torsional spring`, Unit: "N-m/rad"},
	{Keyword: "DTTorDmp", Type: Float, Desc: `Drivetrain torsional damper`, Unit: "N-m/(rad/s)"},
	{Heading: "Furling"},
	{Keyword: "Furling", Type: Bool, Desc: `Read in additional model properties for furling turbine [must currently be FALSE)`, Unit: "flag"},
	{Keyword: "FurlFile", Type: String, Desc: `Name of file containing furling properties (quoted string) [unused when Furling=False]`},
	{Heading: "Tower"},
	{Keyword: "TwrNodes", Type: Int, Desc: `Number of tower nodes used for analysis (-)`},
	{Keyword: "TwrFile", Type: String, Desc: `Name of file containing tower properties (quoted string)`},
	{Heading: "Output"},
	{Keyword: "SumPrint", Type: Bool, Desc: `Print summary data to '<RootName>.sum'`, Unit: "flag"},
	{Keyword: "OutFile", Type: Int, Desc: `Switch to determine where output will be placed: {1: in module output file only; 2: in glue code output file only; 3: both} (currently unused)`},
	{Keyword: "TabDelim", Type: Bool, Desc: `Use tab delimiters in text tabular output file? (currently unused)`, Unit: "flag"},
	{Keyword: "OutFmt", Type: String, Desc: `Format used for text tabular output (except time).  Resulting field should be 10 characters. (quoted string) (currently unused)`},
	{Keyword: "TStart", Type: Float, Desc: `Time to begin tabular output (s) (currently unused)`},
	{Keyword: "DecFact", Type: Int, Desc: `Decimation factor for tabular output {1: output every time step} (-) (currently unused)`},
	{Keyword: "NTwGages", Type: Int, Desc: `Number of tower nodes that have strain gages for output [0 to 9] (-)`},
	{Keyword: "TwrGagNd", Type: Int, Dims: 1, Desc: `List of tower nodes that have strain gages [1 to TwrNodes] (-) [unused if NTwGages=0]`},
	{Keyword: "NBlGages", Type: Int, Desc: `Number of blade nodes that have strain gages for output [0 to 9] (-)`},
	{Keyword: "BldGagNd", Type: Int, Dims: 1, Desc: `List of blade nodes that have strain gages [1 to BldNodes] (-) [unused if NBlGages=0]`},
	{Keyword: "OutList", Type: String, Dims: 1, Format: formatOutList, Parse: parseOutList, Desc: `The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels, (-)`},
})
