package input

var InflowWindSchema = NewSchema("InflowWind", []SchemaEntry{
	{Heading: "InflowWind Input File"},
	{Keyword: "Title", Type: String, Format: formatTitle, Parse: parseTitle},
	{Heading: "General"},
	{Keyword: "Echo", Type: Bool, Desc: `Echo input data to <RootName>.ech (flag)`},
	{Keyword: "WindType", Type: Int, Desc: `switch for wind file type`, Options: []Option{{1, "steady"}, {2, "uniform"}, {3, "binary TurbSim FF"}, {4, "binary Bladed-style FF"}, {5, "HAWC format"}, {6, "User defined"}, {7, "native Bladed FF"}}},
	{Keyword: "PropagationDir", Type: Float, Desc: `Direction of wind propagation (meteorological rotation from aligned with X (positive rotates towards -Y) -- degrees) (not used for native Bladed format WindType=7)`},
	{Keyword: "VFlowAng", Type: Float, Desc: `Upflow angle (degrees) (not used for native Bladed format WindType=7)`},
	{Keyword: "NWindVel", Type: Int, Desc: `Number of points to output the wind velocity`, Options: []Option{{0, "0"}, {1, "1"}, {2, "2"}, {3, "3"}, {4, "4"}, {5, "5"}, {6, "6"}, {7, "7"}, {8, "8"}, {9, "9"}}},
	{Keyword: "WindVxiList", Type: Float, Dims: 1, Desc: `List of coordinates in the inertial X direction`, Unit: "m"},
	{Keyword: "WindVyiList", Type: Float, Dims: 1, Desc: `List of coordinates in the inertial Y direction`, Unit: "m"},
	{Keyword: "WindVziList", Type: Float, Dims: 1, Desc: `List of coordinates in the inertial Z direction`, Unit: "m"},
	{Heading: "Parameters for Steady Wind Conditions [used only for WindType = 1]"},
	{Keyword: "HWindSpeed", Type: Float, Desc: `Horizontal wind speed`, Unit: "m/s"},
	{Keyword: "RefHt", Type: Float, Desc: `Reference height for horizontal wind speed`, Unit: "m"},
	{Keyword: "PLExp", Type: Float, Desc: `Power law exponent`, Unit: "-"},
	{Heading: "Parameters for Uniform wind file [used only for WindType = 2]"},
	{Keyword: "FileName_Uni", Type: String, Desc: `Filename of time series data for uniform wind field`, Unit: "-"},
	{Keyword: "RefHt_Uni", Type: Float, Desc: `Reference height for horizontal wind speed`, Unit: "m"},
	{Keyword: "RefLength", Type: Float, Desc: `Reference length for linear horizontal and vertical sheer`, Unit: "-"},
	{Heading: "Parameters for Binary TurbSim Full-Field files [used only for WindType = 3]"},
	{Keyword: "FileName_BTS", Type: String, Desc: `Name of the Full field wind file to use (.bts)`},
	{Heading: "Parameters for Binary Bladed-style Full-Field files [used only for WindType = 4 or WindType = 7]"},
	{Keyword: "FileNameRoot", Type: String, Desc: `WindType=4: Rootname of the full-field wind file to use (.wnd, .sum); WindType=7: name of the intermediate file with wind scaling values`},
	{Keyword: "TowerFile", Type: Bool, Desc: `Have tower file (.twr) (flag) ignored when WindType = 7`},
	{Heading: "Parameters for HAWC-format binary files  [Only used with WindType = 5] //==="},
	{Keyword: "FileName_u", Type: String, Desc: `name of the file containing the u-component fluctuating wind (.bin)`},
	{Keyword: "FileName_v", Type: String, Desc: `name of the file containing the v-component fluctuating wind (.bin)`},
	{Keyword: "FileName_w", Type: String, Desc: `name of the file containing the w-component fluctuating wind (.bin)`},
	{Keyword: "NX", Type: Int, Desc: `number of grids in the x direction (in the 3 files above)`, Unit: "-"},
	{Keyword: "NY", Type: Int, Desc: `number of grids in the y direction (in the 3 files above)`, Unit: "-"},
	{Keyword: "NZ", Type: Int, Desc: `number of grids in the z direction (in the 3 files above)`, Unit: "-"},
	{Keyword: "DX", Type: Float, Desc: `distance (in meters) between points in the x direction`, Unit: "m"},
	{Keyword: "DY", Type: Float, Desc: `distance (in meters) between points in the y direction`, Unit: "m"},
	{Keyword: "DZ", Type: Float, Desc: `distance (in meters) between points in the z direction`, Unit: "m"},
	{Keyword: "RefHt_Hawc", Type: Float, Desc: `reference height; the height (in meters) of the vertical center of the grid`, Unit: "m"},
	{Heading: "Scaling parameters for turbulence"},
	{Keyword: "ScaleMethod", Type: Int, Desc: `Turbulence scaling method`, Options: []Option{{0, "none"}, {1, "direct scaling"}, {2, "calculate scaling factor based on a desired standard deviation"}}},
	{Keyword: "SFx", Type: Float, Desc: `Turbulence scaling factor for the x direction [ScaleMethod=1]`, Unit: "-"},
	{Keyword: "SFy", Type: Float, Desc: `Turbulence scaling factor for the y direction [ScaleMethod=1]`, Unit: "-"},
	{Keyword: "SFz", Type: Float, Desc: `Turbulence scaling factor for the z direction [ScaleMethod=1]`, Unit: "-"},
	{Keyword: "SigmaFx", Type: Float, Desc: `Turbulence standard deviation to calculate scaling from in x direction [ScaleMethod=2]`, Unit: "m/s"},
	{Keyword: "SigmaFy", Type: Float, Desc: `Turbulence standard deviation to calculate scaling from in y direction [ScaleMethod=2]`, Unit: "m/s"},
	{Keyword: "SigmaFz", Type: Float, Desc: `Turbulence standard deviation to calculate scaling from in z direction [ScaleMethod=2]`, Unit: "m/s"},
	{Heading: "Mean wind profile parameters (added to HAWC-format files)"},
	{Keyword: "URef", Type: Float, Desc: `Mean u-component wind speed at the reference height`, Unit: "m/s"},
	{Keyword: "WindProfile", Type: Int, Desc: `Wind profile type`, Options: []Option{{0, "constant"}, {1, "logarithmic"}, {2, "power law"}}},
	{Keyword: "PLExp_Hawc", Type: Float, Desc: `Power law exponent (used for PL wind profile type only)`, Unit: "-"},
	{Keyword: "Z0", Type: Float, Desc: `Surface roughness length (used for LG wind profile type only)`, Unit: "m"},
	{Keyword: "XOffset", Type: Float, Desc: `Initial offset in +x direction (shift of wind box)`},
	{Heading: "Output"},
	{Keyword: "SumPrint", Type: Bool, Desc: `Print summary data to <RootName>.IfW.sum (flag)`},
	{Keyword: "OutList", Type: String, Dims: 1, Format: formatOutList, Parse: parseOutList, Desc: `The next line(s) contains a list of output parameters.  See OutListParameters.xlsx for a listing of available output channels`, Unit: "-"},
})
